spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/copyright?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password:
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
  mail:
    username: 847070349@qq.com
    password: mtxtchmbuippbeba
    host: smtp.qq.com
    port: 587
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:/mapper/*.xml





